baseURL = "https://zhiqli.github.io/"
languageCode = "zh"
title = "广阔天地大有作为"
theme = "ink-free"
pagination.pagerSize = 5

copyright = "© Copyright zhiqli"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "你想拥有什么，就去追求什么"

	# Optional 64x64 avatar image.
	avatar = "https://raw.githubusercontent.com/zhiqli/imgs/main/avatar.png"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "light"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Stupid footers :)
	#footers = [ 
	#	"你想拥有什么，就去追求什么"
	#]

	# Github base url
	github = "https://github.com/zhiqli"

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = true
	referenceBookWords = 11500.0

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Weekly"
url = "/weekly"
weight = 4

[[menu.main]]
name = "Tags & Stats"
url = "/tags"
weight = 5

[[menu.main]]
name = "Running"
url = "/running"
weight = 6

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/zhiqli/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
